# Model Configuration File
# Settings for all machine learning models

chemprop:
  hidden_size: 300
  depth: 3
  dropout: 0.2
  ffn_hidden_size: 300
  ffn_num_layers: 2
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  warmup_epochs: 2

random_forest:
  n_estimators: 1000
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: sqrt
  bootstrap: true
  class_weight: balanced
  n_jobs: -1
  random_state: 42

xgboost:
  n_estimators: 500
  max_depth: 6
  learning_rate: 0.01
  objective: binary:logistic
  eval_metric: auc
  subsample: 0.8
  colsample_bytree: 0.8
  min_child_weight: 1
  gamma: 0
  reg_alpha: 0.1
  reg_lambda: 1

lightgbm:
  num_leaves: 31
  max_depth: -1
  learning_rate: 0.01
  n_estimators: 500
  objective: binary
  metric: auc
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.1
  reg_lambda: 1

deep_neural_network:
  layers: [ 512, 256, 128, 64 ]
  dropout: 0.3
  activation: relu
  optimizer: adam
  learning_rate: 0.001
  epochs: 100
  batch_size: 64